"""The runtime's name vocabulary: every property, builtin and reference kind it
dispatches on, numbered once for both sides of the bytecode contract.

`runtime/lingo/names.txt` is the source of truth. `python -m director64.names`
regenerates `runtime/lingo/lingo_names.h` (the `LN_*` enum director.c and the
Lingo runtime switch on) and `runtime/lingo/lingo_names.inc` (the sorted text
table `lb_name_id` searches for names that arrive as strings at run time). The
converter maps every interned name to its id at build time, so a generated
handler never pays that search; tests/test_names.py keeps the three files and
the runtime's literal compares in agreement.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NAMES = ROOT / "runtime/lingo/names.txt"
HEADER = ROOT / "runtime/lingo/lingo_names.h"
TABLE = ROOT / "runtime/lingo/lingo_names.inc"

# Compare forms in the runtime whose left side is a name the converter
# interns: the `name` / `property` / `kind` parameters of the dispatch chains.
COMPARE_PATTERNS = [
    r'\bIS\("([^"]+)"\)',
    r'\bNAME_IS\("([^"]+)"\)',
    r'\bPROPERTY_IS\("([^"]+)"\)',
    r'\b(?:eq|equal_text|strcmp)\((?:name|property|kind), *"([^"]+)"\)',
    r"\bLN_([A-Z0-9_]+)\b",
]
RUNTIME_SOURCES = [
    "runtime/director/director.c",
    "runtime/director/d5.inc",
    "runtime/director/d6.inc",
    "runtime/director/d6_events.inc",
    "runtime/director/d10.inc",
    "runtime/lingo/lingo_runtime.c",
]


def load(path: Path = NAMES) -> dict[str, int]:
    names = [line.strip() for line in path.read_text().splitlines() if line.strip()]
    if names != sorted(set(names)):
        raise ValueError("names.txt must be sorted and unique")
    for name in names:
        if not re.fullmatch(r"[a-z_][a-z0-9_]*", name):
            raise ValueError(f"name {name!r} is not a lower-case identifier")
    return {name: i for i, name in enumerate(names)}


def symbol(name: str) -> str:
    return "LN_" + name.upper()


def render_header(names: dict[str, int]) -> str:
    lines = [
        "#ifndef DIRECTOR64_LINGO_NAMES_H",
        "#define DIRECTOR64_LINGO_NAMES_H",
        "// Generated by `python -m director64.names` from runtime/lingo/names.txt;",
        "// do not edit. One id per name the runtime dispatches on, in sorted",
        "// order, so lb_name_id can binary-search the text table.",
        "typedef enum {",
    ]
    lines += [f"  {symbol(name)} = {i}," for name, i in names.items()]
    lines += [
        f"  LB_NAME_COUNT = {len(names)}",
        "} lb_name_t;",
        "// The id of a name that arrives as a string, or LB_NAME_COUNT when the",
        "// runtime dispatches on no such name. Case folds as Lingo does.",
        "unsigned lb_name_id(const char *);",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def render_table(names: dict[str, int]) -> str:
    body = ",\n".join(f'    "{name}"' for name in names)
    return (
        "// Generated by `python -m director64.names` from runtime/lingo/names.txt.\n"
        f"static const char *const lb_name_text[LB_NAME_COUNT] = {{\n{body}}};\n"
    )


def runtime_literals(root: Path = ROOT) -> set[str]:
    """Every name the runtime sources compare against or switch on."""
    found = set()
    for source in RUNTIME_SOURCES:
        text = (root / source).read_text()
        for pattern in COMPARE_PATTERNS:
            for match in re.finditer(pattern, text):
                literal = match.group(1)
                found.add(literal.lower() if pattern.startswith(r"\bLN_") else literal)
    return found


def main() -> None:
    names = load()
    HEADER.write_text(render_header(names))
    TABLE.write_text(render_table(names))
    print(f"{len(names)} names -> {HEADER.name}, {TABLE.name}")


if __name__ == "__main__":
    main()
