"""Generate stable menu metadata before the pinned SDK packages the ROM."""

from __future__ import annotations

import io
import subprocess
import tomllib

from .rom import RomError, metadata_fields


def prepare(game, profile: str):
    if profile not in {"release", "probe"}:
        raise RomError("unknown ROM build profile")
    template = game.directory / "metadata/metadata.ini"
    fields = metadata_fields(
        template.read_bytes(),
        title=game.data["port"]["rom_title"],
        controller_count=game.data["port"].get("controller_count", 1),
    )
    version = tomllib.loads((game.root / "pyproject.toml").read_text())["project"]["version"]
    revision = subprocess.check_output(
        ["git", "-C", str(game.root), "rev-parse", "HEAD"], text=True
    ).strip()
    dirty = bool(
        subprocess.check_output(
            ["git", "-C", str(game.root), "status", "--porcelain", "--untracked-files=normal"]
        )
    )
    build = f"v{version}+{revision[:12]}" + ("-dirty" if dirty else "")
    if profile == "probe":
        build += "-probe"
    fields["short-desc"] = f"{build} - {fields['short-desc']}"
    output = io.StringIO()
    output.write(
        f"; Generated by Director64; edit {template.relative_to(game.root)} instead.\n"
        f"; Game: {game.slug}\n; Source: {game.source['id']}\n"
        f"; Source SHA-256: {game.source['sha256']}\n"
        f"; Revision: {revision}\n; Dirty: {str(dirty).lower()}\n; Profile: {profile}\n"
        "[meta]\n"
    )
    for key, value in fields.items():
        output.write(f"{key} = {value}\n")
    raw = output.getvalue().encode("utf-8")
    metadata_fields(
        raw,
        title=game.data["port"]["rom_title"],
        controller_count=game.data["port"].get("controller_count", 1),
    )
    target = game.work / "n64" / profile / "metadata.ini"
    target.parent.mkdir(parents=True, exist_ok=True)
    if not target.exists() or target.read_bytes() != raw:
        target.write_bytes(raw)
    return target
